let currentLocation=null;
document.addEventListener('DOMContentLoaded',()=>{loadSettings();detectLocation();setupEventListeners();loadChatHistory();});
function loadSettings(){chrome.storage.local.get(['apiKey','view'],(result)=>{if(result.apiKey)document.getElementById('apiKeyInput').value=result.apiKey;if(result.view==='settings'){document.getElementById('settingsPanel').classList.add('active');chrome.storage.local.remove('view');}});}
function setupEventListeners(){document.getElementById('toggleSettings').addEventListener('click',()=>{document.getElementById('settingsPanel').classList.toggle('active');});document.getElementById('saveKey').addEventListener('click',saveApiKey);document.getElementById('sendMessage').addEventListener('click',sendMessage);document.getElementById('messageInput').addEventListener('keypress',(e)=>{if(e.key==='Enter')sendMessage();});document.querySelectorAll('.quick-action-btn').forEach(btn=>{btn.addEventListener('click',()=>{document.getElementById('messageInput').value=btn.dataset.prompt;sendMessage();});});}
function saveApiKey(){const key=document.getElementById('apiKeyInput').value.trim();const statusEl=document.getElementById('keyStatus');if(!key){statusEl.textContent='Please enter an API key';statusEl.className='error';return;}
if(!key.startsWith('sk-ant-')){statusEl.textContent='Invalid API key format';statusEl.className='error';return;}
chrome.storage.local.set({apiKey:key},()=>{statusEl.textContent='API key saved!';statusEl.className='success';document.getElementById('settingsPanel').classList.remove('active');});}
function detectLocation(){if(navigator.geolocation){navigator.geolocation.getCurrentPosition((position)=>{currentLocation={lat:position.coords.latitude,lng:position.coords.longitude};updateLocationDisplay();},(error)=>{document.getElementById('locationCoords').textContent='Access denied';document.getElementById('locationAddress').textContent='Enable location to use full features';});}else{document.getElementById('locationCoords').textContent='Not supported';}}
function updateLocationDisplay(){if(!currentLocation)return;document.getElementById('locationCoords').textContent=`${currentLocation.lat.toFixed(4)}, ${currentLocation.lng.toFixed(4)}`;fetch(`https://nominatim.openstreetmap.org/reverse?format=json&lat=${currentLocation.lat}&lon=${currentLocation.lng}`).then(r=>r.json()).then(data=>{const parts=[data.address.city,data.address.state,data.address.country].filter(Boolean);document.getElementById('locationAddress').textContent=parts.join(', ')||data.display_name;}).catch(()=>{document.getElementById('locationAddress').textContent='Coordinates only';});}
async function sendMessage(){const input=document.getElementById('messageInput');const message=input.value.trim();if(!message)return;const{apiKey}=await chrome.storage.local.get(['apiKey']);if(!apiKey){document.getElementById('settingsPanel').classList.add('active');return;}
addMessage('user',message);input.value='';await getAIResponse(message,apiKey);}
function addMessage(role,content){const container=document.getElementById('chatContainer');const messageEl=document.createElement('div');messageEl.className=`message ${role}`;messageEl.innerHTML=`<div class="message-header">${role==='user'?'👤 You':'🤖 Claude'}</div><div class="message-content">${escapeHtml(content)}</div>`;container.appendChild(messageEl);container.scrollTop=container.scrollHeight;saveToHistory(role,content);}
async function getAIResponse(userMessage,apiKey){const container=document.getElementById('chatContainer');const loadingEl=document.createElement('div');loadingEl.className='message assistant';loadingEl.innerHTML=`<div class="message-header">🤖 Claude <span class="loading"><span class="spinner"></span> thinking...</span></div>`;container.appendChild(loadingEl);container.scrollTop=container.scrollHeight;let systemPrompt='You are a helpful AI assistant that provides insights about locations and places.';let userPrompt=userMessage;if(currentLocation){systemPrompt+=`\n\nThe user is currently at coordinates: ${currentLocation.lat}, ${currentLocation.lng}.`;userPrompt=`${userMessage}\n\nContext: I'm currently located at ${currentLocation.lat.toFixed(4)}, ${currentLocation.lng.toFixed(4)}. Please provide location-relevant information.`;}
try{const response=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':apiKey,'anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true'},body:JSON.stringify({model:'claude-3-haiku-20240307',max_tokens:1024,system:systemPrompt,messages:[{role:'user',content:userPrompt}]})});if(!response.ok){const error=await response.json();throw new Error(error.error?.message||'API request failed');}
const data=await response.json();const aiContent=data.content[0].text;loadingEl.innerHTML=`<div class="message-header">🤖 Claude</div><div class="message-content">${escapeHtml(aiContent)}</div>`;saveToHistory('assistant',aiContent);}catch(error){loadingEl.innerHTML=`<div class="message-header">🤖 Claude</div><div class="message-content"><span class="error">Error: ${escapeHtml(error.message)}</span></div>`;}}
function saveToHistory(role,content){chrome.storage.local.get(['chatHistory'],(result)=>{const history=result.chatHistory||[];history.push({role,content,timestamp:Date.now()});if(history.length>100)history.shift();chrome.storage.local.set({chatHistory:history});});}
function loadChatHistory(){chrome.storage.local.get(['chatHistory'],(result)=>{const history=result.chatHistory||[];const container=document.getElementById('chatContainer');history.forEach(msg=>{const messageEl=document.createElement('div');messageEl.className=`message ${msg.role}`;messageEl.innerHTML=`<div class="message-header">${msg.role==='user'?'👤 You':'🤖 Claude'}</div><div class="message-content">${escapeHtml(msg.content)}</div>`;container.appendChild(messageEl);});});}
function escapeHtml(text){const div=document.createElement('div');div.textContent=text;return div.innerHTML;}
